import {
  LayoutDashboard,
  Waypoints,
  KeyRound,
  BarChart3,
  CreditCard,
  Settings,
  BookOpen,
  Newspaper,
  LifeBuoy,
  ShieldCheck,
  Bug,
  Terminal,
  Plug,
  Activity,
  Globe,
  Logs,
  Home,
  FileText,
  ScrollText,
  UserPlus,
  LogIn,
} from "lucide-react";

export const iconMap = {
  home: Home,
  dashboard: LayoutDashboard,
  tunnels: Waypoints,
  tokens: KeyRound,
  usage: BarChart3,
  billing: CreditCard,
  settings: Settings,
  docs: BookOpen,
  blog: Newspaper,
  support: LifeBuoy,
  changelog: ScrollText,
  terms: FileText,
  auth: ShieldCheck,
  bugs: Bug,
  cli: Terminal,
  integrations: Plug,
  logs: Logs,
  activity: Activity,
  globe: Globe,
  login: LogIn,
  register: UserPlus,
} as const;

export type IconName = keyof typeof iconMap;